=== pelayosl/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es"
elementFormDefault="qualified"
targetNamespace="http://www.uniovi.es"
xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="dimensiones" />
				<xs:element ref="fecha_carrera" />
				<xs:element ref="hora_inicio" />
				<xs:element ref="num_vueltas" />
				<xs:element ref="ubicacion" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas_inicio" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="dimensiones">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud_circuito" type="xs:float" use="required" />
					<xs:attribute name="anchura" type="xs:integer" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud_circuito" type="xs:integer" />
	<xs:element name="anchura" type="xs:integer" />
	<xs:element name="fecha_carrera" type="xs:date" />
	<xs:element name="hora_inicio">
		<xs:simpleType>
			<xs:restriction base="xs:time">
				<xs:minInclusive value="00:00:00.000"/>
				<xs:maxInclusive value="23:59:59.999"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element> 
	<xs:element name="num_vueltas" type="xs:integer" />
	<xs:element name="ubicacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas_inicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud">
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="5000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_final" />
			</xs:sequence>
			<xs:attribute name="sector" type="xs:integer" use="required" />
			<xs:attribute name="distancia" type="xs:float" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas_final">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pelayosl/SEW/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<circuitos
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">  
    <circuito>
        <nombre>Jeddah</nombre>

        <dimensiones longitud_circuito="6.175" anchura="12"></dimensiones>

        <fecha_carrera>2024-03-09</fecha_carrera>
        <hora_inicio>18:00:00.000</hora_inicio>
        <num_vueltas>50</num_vueltas>

        <ubicacion>
            <localidad>Jeddah</localidad>
            <pais>Arabia Saudí</pais>
        </ubicacion>

        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Circuito_de_la_Corniche_de_Yeda</referencia>
            <referencia>https://www.milermeter.com/?r=7570909</referencia>
            <referencia>https://www.gdecarli.it/index.htm</referencia>
        </referencias>

        <fotos>
            <foto>F1Desktop/multimedia/imagenes/jeddah_noche.jpg</foto>
        </fotos>

        <videos>
            <video></video>
        </videos>

        <coordenadas_inicio>
            <longitud>39°06'16.3"E</longitud>
            <latitud>21°37'57.3"N </latitud>
            <altitud>2</altitud>
        </coordenadas_inicio>

        <tramos>
            <tramo distancia="38.54" sector="1">
                <coordenadas_final>
                    <longitud>39°06'12"E</longitud>
                    <latitud>21°38'05"N</latitud>
                    <altitud>2.94</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="62.88" sector="2">
                <coordenadas_final>
                    <longitud>39°06'10"E</longitud>
                    <latitud>21°38'05"N</latitud>
                    <altitud>2.27</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="72.08" sector="3">
                <coordenadas_final>
                    <longitud>39°06'11"E</longitud>
                    <latitud>21°38'08"N</latitud>
                    <altitud>2.27</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="76.70" sector="4">
                <coordenadas_final>
                    <longitud>39°06'11"E</longitud>
                    <latitud>21°38'10"N</latitud>
                    <altitud>2.19</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="255.28" sector="5">
                <coordenadas_final>
                    <longitud>39°06'10"E</longitud>
                    <latitud>21°38'19"N</latitud>
                    <altitud>2.72</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="39.87" sector="6">
                <coordenadas_final>
                    <longitud>39°06'09"E</longitud>
                    <latitud>21°38'19"N</latitud>
                    <altitud>3.42</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="75.61" sector="7">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'21"N</latitud>
                    <altitud>3.50</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="124.27" sector="8">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'25"N</latitud>
                    <altitud>3.50</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="105.05" sector="9">
                <coordenadas_final>
                    <longitud>39°06'08"E</longitud>
                    <latitud>21°38'28"N</latitud>
                    <altitud>2.112</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="38.83" sector="10">
                <coordenadas_final>
                    <longitud>39°06'08"E</longitud>
                    <latitud>21°38'29"N</latitud>
                    <altitud>2.88</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="50.81" sector="11">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'30"N</latitud>
                    <altitud>3.50</altitud>
                </coordenadas_final>
            </tramo>

            <tramo distancia="70.55" sector="12">
                <coordenadas_final>
                    <longitud>39°06'05"E</longitud>
                    <latitud>21°38'32"N</latitud>
                    <altitud>3.19</altitud>
                </coordenadas_final>
            </tramo>
            
            <tramo distancia="79.25" sector="13">
                <coordenadas_final>
                    <longitud>39°06'05"E</longitud>
                    <latitud>21°38'35"N</latitud>
                    <altitud>3.50</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="98.5" sector="14">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'37"N</latitud>
                    <altitud>3.48</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="75.32" sector="15">
                <coordenadas_final>
                    <longitud>39°06'09"E</longitud>
                    <latitud>21°38'39"N</latitud>
                    <altitud>2.26</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="132.63" sector="16">
                <coordenadas_final>
                    <longitud>39°06'10"E</longitud>
                    <latitud>21°38'43"N</latitud>
                    <altitud>1.75</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="106.13" sector="17">
                <coordenadas_final>
                    <longitud>39°06'11"E</longitud>
                    <latitud>21°38'46"N</latitud>
                    <altitud>2.04</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="353.39" sector="18">
                <coordenadas_final>
                    <longitud>39°06'10"E</longitud>
                    <latitud>21°38'58"N</latitud>
                    <altitud>2.27</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="279.83" sector="19">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'55"N</latitud>
                    <altitud>3.81</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="77.82" sector="20">
                <coordenadas_final>
                    <longitud>39°06'08"E</longitud>
                    <latitud>21°38'53"N</latitud>
                    <altitud>3.49</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="199.57" sector="21">
                <coordenadas_final>
                    <longitud>39°06'08"E</longitud>
                    <latitud>21°38'47"N</latitud>
                    <altitud>2.85</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="55.76" sector="22">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'45"N</latitud>
                    <altitud>2.28</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="98.64" sector="23">
                <coordenadas_final>
                    <longitud>39°06'06"E</longitud>
                    <latitud>21°38'42"N</latitud>
                    <altitud>2.73</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="88.77" sector="24">
                <coordenadas_final>
                    <longitud>39°06'05"E</longitud>
                    <latitud>21°38'40"N</latitud>
                    <altitud>2.74</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="82.20" sector="25">
                <coordenadas_final>
                    <longitud>39°06'03"E</longitud>
                    <latitud>21°38'38"N</latitud>
                    <altitud>2.74</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="256.11" sector="26">
                <coordenadas_final>
                    <longitud>39°06'04"E</longitud>
                    <latitud>21°38'30"N</latitud>
                    <altitud>3.32</altitud>
                </coordenadas_final>
            
            </tramo>
            <tramo distancia="201.87" sector="27">
                <coordenadas_final>
                    <longitud>39°06'05"E</longitud>
                    <latitud>21°38'24"N</latitud>
                    <altitud>3.43</altitud>
                </coordenadas_final>
            </tramo>

            <tramo distancia="197.18" sector="28">
                <coordenadas_final>
                    <longitud>39°06'07"E</longitud>
                    <latitud>21°38'18"N</latitud>
                    <altitud>2.88</altitud>
                </coordenadas_final>
            </tramo>
